config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :long_urls, only: [:index]
  resources :short_urls, only: [:create, :show]

  get '/shortened/:short_url', to: 'short_urls#redirect_url', as: 'redirect_url'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "long_urls#show"
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/long_url.rb
class LongUrl < ApplicationRecord
  has_many :short_urls, dependent: :destroy
  validates :url, presence: true, url: true, uniqueness: true
end

app/models/short_url.rb
class ShortUrl < ApplicationRecord
  belongs_to :long_url
  belongs_to :user

  validates :url, presence: true, uniqueness: true
  validates :alias, length: { maximum: 16 }, uniqueness: true, allow_blank: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :short_urls, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || long_urls_path
  end

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation)}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/long_urls_controller.rb
class LongUrlsController < ApplicationController
  def index
  end
end

app/controllers/short_urls_controller.rb
class ShortUrlsController < ApplicationController
  before_action :get_url, only: [:show]

  def show
  end

  def create
    shortened_url = create_short_url
    @long_url = LongUrl.create!(url: short_url_params[:long_url])
    @short_url = current_user.short_urls.new(long_url: @long_url, url: shortened_url)
    if @short_url.save
      redirect_to @short_url
      flash[:success] = "Short URL created successfully"
    else
      redirect_to long_urls_path
      flash[:notice] = "Could not create short URL"
    end
  end

  def redirect_url
    @short_url = ShortUrl.find_by(url: params[:short_url])
    if @short_url
      redirect_to @short_url.long_url.url, allow_other_host: true # pass the url to the browser
    else
      render file: "#{Rails.root}/public/404.html", status: 404
    end
  end

  private

  def short_url_params
    params.require(:short_url).permit(:url, :alias).merge(long_url: params[:url])
  end

  def create_short_url
    custom_name = short_url_params[:alias]
    if custom_name.present?
      @short_url = custom_name
    else
      hashed_string = Digest::SHA1.hexdigest(short_url_params[:long_url])[0..5]
      @short_url = hashed_string
    end
  end

  def get_url
    @short_url = ShortUrl.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/long_urls_helper.rb
module LongUrlsHelper
end

app/helpers/short_urls_helper.rb
module ShortUrlsHelper
end

app/views/home/index.html.erb
<main class="home-container">
  <h1>URL Shortener</h1>
  <section class="home-section">
    <% if user_signed_in? %>
      <h4 class="username">Hi! <%= current_user.name.capitalize %> </h4>
      <%= button_to 'Shorten Url', long_urls_path, method: :get, class: 'home-btn' %>
    <% else %>
      <h4 class="username">Welcome</h4>
      <div class="buttons-div">
        <%= button_to 'LOG IN', new_user_session_path, method: :get, class: 'home-btn devise-btn' %>
        <%= button_to 'SIGN UP', new_user_registration_path, method: :get, class: 'home-btn devise-btn' %>
      </div>
    <% end %>
    <%= render partial: "shared/sign_out" %>
  </section>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
    <%= yield %>
  </body>
</html>

app/views/long_urls/index.html.erb
<main class="container">
  <%= form_tag "/short_urls", data: {controller: 'url', url_alias_count_value: 16, url_over_limit_class: 'warning-text'} do %>
    <div class="field input-div">
      <%= label_tag :url, 'Enter Url' %>
      <p class="format">(Format: https://...)</p>
      <%= text_field_tag :url, '', class: 'text-input' %>
    </div>
    <%= fields_for :short_url do |f| %>
      <div class="field input-div">
        <%= f.label :alias, 'Create Custom Endpoint' %>
        <%= f.text_field :alias, class: 'text-input', data: {url_target: 'aliasField', action: "keyup->url#change"} %>
        <p data-url-target="maximumAliasOutput" class="output"></p>
      </div>
    <% end %>
    <div class="submit-btn-div">
      <%= submit_tag 'Shorten Url' %>
    </div>
  <% end %>
  <%= render partial: "shared/sign_out" %>
</main>

app/views/shared/_sign_out.html.erb
<%= button_to 'LOG OUT', destroy_user_session_path, method: :delete, class: 'links faded' if user_signed_in? %>

app/views/short_urls/show.html.erb
<main class="container">
  <p class="output">Click the link below to visit site</p>
  <%= link_to "#{@short_url.url}", redirect_url_path(@short_url.url), target: "_blank", class: 'links url-link' %>
</main>